services:
  syslog-ng:
    image: balabit/syslog-ng:4.6.0
    container_name: syslog-ng
    restart: unless-stopped
    privileged: true
    user: root
    cap_add: 
      - NET_BIND_SERVICE
    ports:
      - "5140:5140/udp"   # UDP port
      - "10514:10514/tcp"   # TCP port
      - "6514:6514/tcp" # TLS port
    volumes:
      - ./syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf:ro   # syslog-ng.conf 
      - ./logs:/var/log/syslog-ng                           # syslog-ng messages (log file)
      - ./certs:/etc/syslog-ng/certs                         # storage position of certificates
    environment:
      - TZ=Asia/Taipei
    networks:
      - syslog-net

networks:
  syslog-net:
    driver: bridge
